Import('*')

Source('energy_mgmt.cc')
Source('energy_port.cc')
Source('energy_object.cc')
Source('state_machine.cc')
Source('harvest.cc')
Source('two_thres.cc')

SimObject('EnergyMgmt.py')
SimObject('BaseEnergySM.py')
SimObject('SimpleEnergySM.py')
SimObject('BaseHarvest.py')
SimObject('SimpleHarvest.py')
SimObject('TwoThresSM.py')

DebugFlag('EnergyMgmt')
